music/urls.py
from django.urls import path

from . import views

app_name = 'music'

urlpatterns = [
    # music
    path('', views.IndexView.as_view(), name='index'),

    # registration link
    path('register/', views.UserFormView.as_view(), name='register'),

    # music/id/
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
    # /music/album/add/
    path('<int:album-add/pk>/', views.AlbumCreate.as_view(), name='album-add'),

    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),

    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),

]

music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=255)
    album_title = models.CharField(max_length=255)
    genre = models.CharField(max_length=250)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.artist + '-' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=20)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import UserForm
from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # displays blank form for new user
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # processes new user data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # clean normalized data
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return User Objects if credentials are correct/valid
            user = authenticate(username=username, email=email, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album {% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add New Album </h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form action="" class="form-horizontal" enctype="multipart/form-data" method="post" role="form">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-success" type="submit">Submit</button>

                            </div>
                        </div>

                    </form>

                </div>

            </div>

        </div>

    </div>

</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}KOnnect{% endblock %}</title>
    {% load static %}
    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>
    <link href="{% static 'music/style.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class=".container-fluid">
        <div class="navbar-header">
            <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                    class="navbar-toggler" data-target="#topNavBar" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>

            <span class="navbar-brand mb-0 h1">KOnnect Music</span>

        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <u1 class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/music/">
                        <svg class="bi bi-mic-fill" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M5 3a3 3 0 016 0v5a3 3 0 01-6 0V3z"/>
                            <path clip-rule="evenodd"
                                  d="M3.5 6.5A.5.5 0 014 7v1a4 4 0 008 0V7a.5.5 0 011 0v1a5 5 0 01-4.5 4.975V15h3a.5.5 0 010 1h-7a.5.5 0 010-1h3v-2.025A5 5 0 013 8V7a.5.5 0 01.5-.5z"
                                  fill-rule="evenodd"/>
                        </svg>&nbsp; Albums

                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <svg class="bi bi-music-note-beamed" fill="currentColor" height="1em" viewBox="0 0 16 16"
                             width="1em" xmlns="http://www.w3.org/2000/svg">
                            <path d="M6 13c0 1.105-1.12 2-2.5 2S1 14.105 1 13c0-1.104 1.12-2 2.5-2s2.5.896 2.5 2zm9-2c0 1.105-1.12 2-2.5 2s-2.5-.895-2.5-2 1.12-2 2.5-2 2.5.895 2.5 2z"/>
                            <path d="M5 2.905a1 1 0 01.9-.995l8-.8a1 1 0 011.1.995V3L5 4V2.905z"/>
                        </svg>&nbsp; Songs

                    </a>
                </li>

            </u1>
            <form class="form-inline">
                <input aria-label="Search" class="form-control mr-sm-2" placeholder="Search" type="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

            <u1 class="navbar-nav mr-auto justify-content-right">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'music:album-add' %}">
                        <svg class="bi bi-upload" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                             xmlns="http://www.w3.org/2000/svg">
                            <path clip-rule="evenodd"
                                  d="M.5 8a.5.5 0 01.5.5V12a1 1 0 001 1h12a1 1 0 001-1V8.5a.5.5 0 011 0V12a2 2 0 01-2 2H2a2 2 0 01-2-2V8.5A.5.5 0 01.5 8zM5 4.854a.5.5 0 00.707 0L8 2.56l2.293 2.293A.5.5 0 1011 4.146L8.354 1.5a.5.5 0 00-.708 0L5 4.146a.5.5 0 000 .708z"
                                  fill-rule="evenodd"/>
                            <path clip-rule="evenodd" d="M8 2a.5.5 0 01.5.5v8a.5.5 0 01-1 0v-8A.5.5 0 018 2z"
                                  fill-rule="evenodd"/>
                        </svg>&nbsp; Upload Album
                        &nbsp;
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/music/register/">
                        Signup
                        &nbsp;
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="/music/">
                        <svg class="bi bi-house-fill" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                             xmlns="http://www.w3.org/2000/svg">
                            <path clip-rule="evenodd"
                                  d="M8 3.293l6 6V13.5a1.5 1.5 0 01-1.5 1.5h-9A1.5 1.5 0 012 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 01.5-.5h1a.5.5 0 01.5.5z"
                                  fill-rule="evenodd"/>
                            <path clip-rule="evenodd"
                                  d="M7.293 1.5a1 1 0 011.414 0l6.647 6.646a.5.5 0 01-.708.708L8 2.207 1.354 8.854a.5.5 0 11-.708-.708L7.293 1.5z"
                                  fill-rule="evenodd"/>
                        </svg>&nbsp; Homepage

                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <svg class="bi bi-power" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                             xmlns="http://www.w3.org/2000/svg">
                            <path clip-rule="evenodd"
                                  d="M5.578 4.437a5 5 0 104.922.044l.5-.866a6 6 0 11-5.908-.053l.486.875z"
                                  fill-rule="evenodd"/>
                            <path clip-rule="evenodd" d="M7.5 8V1h1v7h-1z" fill-rule="evenodd"/>
                        </svg>&nbsp; Logout
                    </a>
                </li>

            </u1>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %}Album Details {% endblock %}

{% block body %}
<div class="container-fluid songs-container">
    <div class="row">
        <!--left Album info-->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:details' album.id %}">
                        <img alt="" class="img.responsive" height="900" src="{{ album.album_logo.url }}" width="800">
                    </a>
                    <h1>{{ album.album_title }}</h1>
                    <h2>{{ album.genre }}</h2>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>
        <!--Right Song info-->
        <div class="col-sm-8 col-md-9">
            <u1 class="nav nav-pills" style="margin-bottom:10px;">
                <li class="active"><a href="#i2">View All Songs</a></li>
            </u1>
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="songs">
                        <thread>
                            <tr>
                                <th style="background-color:white;color:green;padding:5px;text-align:center">Title</th>
                                <th style="background-color:white;color:green;padding:5px;text-align:center">Audio
                                    File
                                </th>
                                <th style="background-color:white;color:green;padding:5px;text-align:center">Actions
                                </th>
                            </tr>
                        </thread>
                        {% for song in album.song_set.all %}
                        <tr id="i2">
                            <td style="color:blue;">{{ song.song_title }}</td>
                            <br>
                            <td style="color:tomato">{{ song.file_type }}</td>
                            <br>
                            <td>
                                <a class="btn btn-default btn-sm btn-favorite" href="#" title="Make Favorite"></a>
                                <svg class="bi bi-heart-fill" fill="currentColor" height="1em" style="color:red;"
                                     viewBox="0 0 16 16" width="1em" xmlns="http://www.w3.org/2000/svg">
                                    <path clip-rule="evenodd"
                                          d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                          fill-rule="evenodd"/>
                                </svg>
                                <button class="btn btn-default btn-sm" title="Play" type="submit"></button>
                                >
                                <svg class="bi bi-play-fill" fill="currentColor" height="1em" style="color:white;"
                                     viewBox="0 0 16 16" width="1em" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M11.596 8.697l-6.363 3.692c-.54.313-1.233-.066-1.233-.697V4.308c0-.63.692-1.01 1.233-.696l6.363 3.692a.802.802 0 010 1.393z"/>
                                </svg>
                                <button class="btn btn-default btn-sm" title="Download" type="submit"></button>
                                <svg class="bi bi-download" fill="currentColor" height="1em"
                                     style="color:rgb(120,85,200)" viewBox="0 0 16 16" width="1em"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path clip-rule="evenodd"
                                          d="M.5 8a.5.5 0 01.5.5V12a1 1 0 001 1h12a1 1 0 001-1V8.5a.5.5 0 011 0V12a2 2 0 01-2 2H2a2 2 0 01-2-2V8.5A.5.5 0 01.5 8z"
                                          fill-rule="evenodd"/>
                                    <path clip-rule="evenodd"
                                          d="M5 7.5a.5.5 0 01.707 0L8 9.793 10.293 7.5a.5.5 0 11.707.707l-2.646 2.647a.5.5 0 01-.708 0L5 8.207A.5.5 0 015 7.5z"
                                          fill-rule="evenodd"/>
                                    <path clip-rule="evenodd" d="M8 1a.5.5 0 01.5.5v8a.5.5 0 01-1 0v-8A.5.5 0 018 1z"
                                          fill-rule="evenodd"/>
                                </svg>
                            </td>
                            <br>
                        </tr>
                        {% endfor %}
                    </table>
                </div>

            </div>

        </div>

    </div>

</div>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %}KOnnect Music Homepage {% endblock %}
{% block body %}
<div class="albums-container container-fluid">
    <div class="row">
        {% for album in all_albums %}
        <div class="col-sm-4 col-lg-2">
            <div class="thumbnail">
                <a href="{% url 'music:details' album.id %}">
                    <img alt="" class="img.responsive" height="250" src="{{ album.album_logo.url }}" width="250">

                </a>
                <div class="caption">
                    <h2>{{ album.artist }}</h2>
                    <h4>{{ album.album_title }}</h4>

                    <!--details-->
                    <a class="btn btn-primary btn-sm" href="{% url 'music:details' album.id %}">View Details</a>

                    <!--Delete button-->
                    <form action="#" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input name="album_id" type="hidden" value="{{ album.id }}">
                        <button class="btn btn-default btn-sm" type="submit">
                            <svg class="bi bi-trash-fill" fill="currentColor" height="1em" viewBox="0 0 16 16"
                                 width="1em" xmlns="http://www.w3.org/2000/svg">
                                <path clip-rule="evenodd"
                                      d="M2.5 1a1 1 0 00-1 1v1a1 1 0 001 1H3v9a2 2 0 002 2h6a2 2 0 002-2V4h.5a1 1 0 001-1V2a1 1 0 00-1-1H10a1 1 0 00-1-1H7a1 1 0 00-1 1H2.5zm3 4a.5.5 0 01.5.5v7a.5.5 0 01-1 0v-7a.5.5 0 01.5-.5zM8 5a.5.5 0 01.5.5v7a.5.5 0 01-1 0v-7A.5.5 0 018 5zm3 .5a.5.5 0 00-1 0v7a.5.5 0 001 0v-7z"
                                      fill-rule="evenodd"/>
                            </svg>&nbsp;Delete
                        </button>

                    </form>

                    <!--Favorite button-->
                    <a class="btn btn-default btn-sm btn-favorite" href="#"></a>
                    <svg class="bi bi-heart-fill" fill="currentColor" height="1em" viewBox="0 0 16 16" width="1em"
                         xmlns="http://www.w3.org/2000/svg">
                        <path clip-rule="evenodd"
                              d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"
                              fill-rule="evenodd"/>
                    </svg>&nbsp;Favorite
                </div>

            </div>

        </div>
        {% endfor %}

    </div>

</div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create New Account </h3>
                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form action="" class="form-horizontal" enctype="multipart/form-data" method="post" role="form">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-success" type="submit">Submit</button>

                            </div>
                        </div>

                    </form>

                </div>

            </div>

        </div>

    </div>

</div>
{% endblock %}